### ISSUE TITLE
Add a win/lose state

### ISSUE THREAD

**Issue by katmathematics** [noahwhlim/hackuiowa-2023#6]
Make the game terminate on some condition and display a pop up saying the player won/lost/whatever. I'd maybe do after like 3 wrong answers the player loses, else if they complete X amount of prompts they win, but the termination condition can be up to the discretion of whoever implements it. Whatever works will be sufficient.

**Comment by noahwhlim** [comment]
Added win condition when score is 5. New modal will pop up and allow user to refresh the page to play again
